info:
  app:
    name: "Foodservice development "
    description: "this is a dev development and this a configuration of food server in the config server food service"
    version: "2.0 under development"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro
    username: root
   # password: 12345@shubham
     password: "{cipher}6f065804819e0f657fdb1b2d60ae8741f16e6956524236401ad8bd8fcf3435f7"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: FOOD-SERVICE

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true
