info:
  app:
    name: "Foodservice development "
    description: "this is a dev development and this a configuration of food server in the config server food service"
    version: "1.0 this is new versions"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/micro
    username: root
    password: 12345@shubham
  
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: FOOD-SERVICE

server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true
